// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3dsooo7huNhcYTNnnfMU8NRooLbYQ2b4',
    appId: '1:421154562554:web:ead5bb06ec41a67a628443',
    messagingSenderId: '421154562554',
    projectId: 'batterylog-ce404',
    authDomain: 'batterylog-ce404.firebaseapp.com',
    storageBucket: 'batterylog-ce404.appspot.com',
    measurementId: 'G-LWVFVJ6NDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ6EU8ShQcVstvtSCA2Lpeiv6nR-sZq1U',
    appId: '1:421154562554:android:a3517f9af79c80e6628443',
    messagingSenderId: '421154562554',
    projectId: 'batterylog-ce404',
    storageBucket: 'batterylog-ce404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF2MnoxFn935au27Hn8OWZvKNnvFrceMI',
    appId: '1:421154562554:ios:1e1768c9f9ac977d628443',
    messagingSenderId: '421154562554',
    projectId: 'batterylog-ce404',
    storageBucket: 'batterylog-ce404.appspot.com',
    iosClientId: '421154562554-0ccm2qq508tqullcrluq4l00au7433v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.baterryLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF2MnoxFn935au27Hn8OWZvKNnvFrceMI',
    appId: '1:421154562554:ios:1e1768c9f9ac977d628443',
    messagingSenderId: '421154562554',
    projectId: 'batterylog-ce404',
    storageBucket: 'batterylog-ce404.appspot.com',
    iosClientId: '421154562554-0ccm2qq508tqullcrluq4l00au7433v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.baterryLog',
  );
}
